### ISSUE TITLE
Received Memory warning while downloading 250+ MB file

### ISSUE THREAD

**Issue by ghost** [robertmryan/download-manager#2]
Hi,

I am getting memory warning after downloading 230MB size out of 250MB.

**Comment by robertmryan** [comment]
I'm not sure what to say. I just did a test downloading a 400+mb file, and looking at allocations they hovered at roughly 1.5mb total allocations, and peaked at 3.5mb. This isn't the entire download, but this is the basic pattern, where memory isn't not continually being consumed, but rather is being released properly as it goes along:

![allocations](https://f.cloud.github.com/assets/1530768/404234/6727fdee-a93d-11e2-82b4-b1e840048427.png)

Can you run your app through the profiler and perhaps show me what your allocations look like? And can you confirm that you don't have zombies turned on or anything like that? 

Are you sure your problem is during the download and not your processing afterward (if any)? What is your file?

**Comment by robertmryan** [comment]
I don't know if [this post](http://stackoverflow.com/questions/16113426) is you, but when I use those `mach.h` memory routines, it's entirely consistent with what Allocations is telling me: It's not consuming memory.
