### ISSUE TITLE
weak reference error

### ISSUE THREAD

**Issue by rickroll** [robertmryan/download-manager#4]
Download.h & DownloadManager.h use these weak references:

@property (nonatomic, weak) id<DownloadDelegate> delegate;
@property (nonatomic, weak) id<DownloadManagerDelegate> delegate;

cause an error:
ARC Weak References
The current deployment target does not support automated __weak references

This is due to me building the project in a new iOS version.

I can fix this by changing weak to unsafe_unretained.  unsafe_unretained does act a bit different so I wanted to mention that this should be update but also do you see any issues with changing this?

**Comment by robertmryan** [comment]
@rickroll 

You could theoretically do that (or probably use `assign`), but you'd really have to pour through the code and  manually convert the code to non-ARC and make sure that you put in all of the necessary `retain`, `release` and `autorelease` statements. If you run the code through the static analyzer ("Analyze" on the Xcode "Product" menu), it would point out a bunch of leaks, which would help identify those things you'd have to change.

Probably easier, just flag the `Download.m` and `DownloadManager.m` files with the `-fobjc-arc` flag under the "Compile Sources" section of the "Build Phases" section of the target settings. That will tell the compiler that although it's a non-ARC project, compile those two .m files as ARC.

![screen shot 2013-12-05 at 4 00 21 pm](https://f.cloud.github.com/assets/1530768/1687054/504fdf20-5df0-11e3-9d63-d8e17881c786.png)

**Comment by rickroll** [comment]
I'm actually using ARC, but I was getting errors from the weak reference. Turned out xcode was just having some problems and creating build errors where there wasn't any.  Thanks for the extra info on this!

**Comment by robertmryan** [comment]
@rickroll Ah. I assumed you were getting this error because you were not using ARC. You'd also get that error if your base target was earlier than iOS 5.0 (because while iOS 4.3 supports ARC, it doesn't support the automatic `nil`-ing of `weak` references). In that case, shifting to `unsafe_unretained` would probably do it, though (like in all code that predated `weak` properties) you'd want to make sure that the delegate object (e.g. your view controller or what have you) would make sure to manually `nil` the `delegate` property in `Download` and/or `DownloadManager` in its `dealloc` method. 

But it sounds like you solved the problem, regardless. Happy coding!
