### ISSUE TITLE
Starting a download from a separate class 

### ISSUE THREAD

**Issue by nickivey** [robertmryan/download-manager#6]
DownloadTableView *download = [[DownloadTableView alloc] init];
 [download queueAndStartDownloads:_downloadURL];

Using the code above doesnt seem to set the delegate right. 
When the app runs it will download the file but will not update any of the delegate methods

**Comment by robertmryan** [comment]
Look at the example in MasterViewController.m. But, you don't appear to set set the delegate. use `initWithDelegate` rather than `init`. Also, use class property for the download manager instance, rather than locals variable. Thus:

```
@property (strong, nonatomic) DownloadManager *downloadManager;
```

and

```
self.downloadManager = [[DownloadManager alloc] initWithDelegate:self];

// queue the files to be downloaded

for (NSString *urlString in urlStrings) {
    NSString *downloadFilename = [downloadFolder stringByAppendingPathComponent:[urlString lastPathComponent]];
    NSURL *url = [NSURL URLWithString:urlString];

    [self.downloadManager addDownloadWithFilename:downloadFilename URL:url];
}
```

**Comment by nickivey** [comment]
It calls the delegate methods but the table view still does not update

**Comment by robertmryan** [comment]
Are you seeing _anything_ in your tableview? If you're seeing the delegate methods getting called, but you're not seeing the updates in your table, it's probably something like a failure to hook up the `IBOutlet` or failure to specify the `dataSource` and `delegate` of the tableview. If you're seeing the cells, but the progress view isn't changing (if you're using a progress view at all), it could be a type conversion error or failure to handle `expectedContentLength` of less than zero (some servers gzip their responses, and thus there's no meaningful `expectedContentLength`, so it's impossible to perform a "percent complete" calculation).

If I'm to help you, you have to be far more specific about the precise behavior you're seeing, what debugging/diagnostics you've done. But if you're seeing the delegate methods called, it sounds like an issue in your tableview code, not the downloader.

**Comment by nickivey** [comment]
I see nothing on the table when triggering the download from my other class but if I call it from 
viewdidload 
[self queueAndStartDownloads:@"",@""];
Everything works fine

**Comment by robertmryan** [comment]
@nickivey If this isn't working when you use it from another class, I can only suggest that you examine the lifecycle of that instance of that other class. For example, put breakpoints in the `init` and `dealloc` methods, and make sure it's being instantiated the way you think it is. Without seeing that code for that other class (including not only that classes' code, but also show where you instantiate it, I cannot offer you any counsel.

**Comment by nickivey** [comment]
https://github.com/nickivey/iOnion/ If you have time would appreciate you checking it out. Try downloading a mp3 file with the browser and see what happens.

The Class that the download starts in is WebViewController
The Class that tracks it is DownloadTableView

**Comment by robertmryan** [comment]
I'll take a look later today.

**Comment by robertmryan** [comment]
@nickivey I can't compile this as some sources are missing (`DirectoryWatcher`). Thus it's really hard to diagnose the issue. I'm left with just reading code trying to find something wrong.

A couple of things:
1. What does seem like a problem is that your `WebViewController` (which I assume is initiating the download) is calling the `sharedManager` method of `DownloadTableView` (a singleton-style pattern), but this results in instantiating yet another `DownloadTableView`! Worse, this new instance has no `view` associated with it, so any attempt to update  the UI in the delegate methods will be for naught.
   
   You should either (a) grab the `DownloadTableView` instance from the tab controller; (b) have your app delegate save it in some class property which you can grab from that; or (c) have your `DownloadTableView` save the instance in some global/static and then have some class method that retrieves that for you. But the `sharedManager` pattern is not valid here. You have to call `queueAndStartDownloads` on the instance of the app delegate added to be tab controller.
2. Second, your instantiation of `DownloadTableView` is a little curious:
   
   ```
   DownloadTableView *view2 = [[DownloadTableView alloc] init];
   view2 = [[UIStoryboard storyboardWithName:@"DownloadTableView" bundle:nil] instantiateViewControllerWithIdentifier:@"Download"];
   ```
   
   That first line instantiates a `DownloadTableView`, but the second line discards it and instantiates another. You can get rid of that `alloc`/`init`, because when you instantiate a storyboard scene, if that scene has a base class, that will be instantiated for you. This is unrelated to the main problem, but there is a pattern here (and forgive me for saying this) that you're not being very careful with your view controller instances.
3. Another issue is that I'd expect you to perform a `reloadData` or `insertRowsAtIndexPaths:withRowAnimation:` in `queueAndStartDownloads`. When you add an item to the model backing your table view, you have to tell the table view to query the data source accordingly.

**Comment by nickivey** [comment]
It works using the tab bar controller to call the method. 
Thank you! I really appreciate the help, this is the first project I have worked on that required me to work with Views programmatically.
