### ISSUE TITLE
NSURLConnection to NSURLSession

### ISSUE THREAD

**Issue by praveenkumar56060** [robertmryan/download-manager#7]
Any idea to implement this kit from `NSURLConnection` to `NSURLSession` methods?

**Comment by robertmryan** [comment]
This `NSOperation`-based download pattern is less compelling in the world with `NSURLSession`, because if you were doing lots of downloads with `NSURLSession`, you'd undoubtedly want to use a background session (which keeps requests going even after you leave the app), but `NSOperation` doesn't make sense in that context. You really should just go ahead and implement background based `NSURLSession`. See the latter part of this answer http://stackoverflow.com/a/20808917/1271826 or just google "Background NSURLSession".
